APP_NAME = "PrintingAlley"
KEYCHAIN_NAME = ENV["KEYCHAIN_NAME"]
KEYCHAIN_PASSWORD = ENV["KEYCHAIN_PASSWORD"]
DEV_SCHEME = "PrintingAlley-DEV"
PROD_SCHEME = "PrintingAlley-PROD"

# ✅ 기본 플랫폼을 ios 로 설정하여 fastlane [lane name] 으로 쉽게 실행가능.(원래 fastlane [platfrom name] [lane name] 으로 실행해야 함)
default_platform(:ios)


platform :ios do 
  # ✅ 인증서를 키체인에 저장하기
  desc "Save To Keychain"
  lane :set_keychain do
    create_keychain(
      name: "#{KEYCHAIN_NAME}", # 새로 생성될 키체인의 이름을 지정합니다. 
      password: "#{KEYCHAIN_PASSWORD}", # 새로운 키체인을 만들 때 설정할 비밀번호를 지정합니다
      default_keychain: true, # 완성된 키체인을 시스템의 기본 키체인으로 설정합니다.
      unlock: true, # 키체인을 생성한 후에 자동으로 언락합니다. 즉, 비밀번호를 입력하지 않고도 해당 키체인에 액세스할 수 있습니다
      timeout: 3600, # 키체인이 언락된 상태를 유지하는 시간을 지정합니다. 여기서는 3600초(1시간) 동안 언락 상태를 유지합니다.
      lock_when_sleeps: false #  시스템이 슬립 모드로 들어갈 때 키체인을 잠그도록 설정합니다.
    )

    # ✅ 인증서를 특정 키체인에 가져오는 데 사용됩니다. 
    import_certificate(
      certificate_path: "Tuist/Signing/PrintingAlley.PROD.cer", # 가져올 인증서의 경로를 지정합니다. 이는 로컬 파일 시스템에 있는 인증서 파일의 경로여야 합니다.
      keychain_name: "#{KEYCHAIN_NAME}", # 인증서를 가져올 키체인의 이름을 지정합니다. 해당 키체인은 이미 생성되어 있어야 합니다. 
      keychain_password: "#{KEYCHAIN_PASSWORD}" # 키체인의 비밀번호를 제공합니다. 이 비밀번호는 키체인을 언락하는 데 사용됩니다.
    )

      # ✅ 인증서를 특정 키체인에 가져오는 데 사용됩니다. 
      import_certificate(
        certificate_path: "Tuist/Signing/PrintingAlley.DEV.cer", # 가져올 인증서의 경로를 지정합니다. 이는 로컬 파일 시스템에 있는 인증서 파일의 경로여야 합니다.
        keychain_name: "#{KEYCHAIN_NAME}", # 인증서를 가져올 키체인의 이름을 지정합니다. 해당 키체인은 이미 생성되어 있어야 합니다. 
        keychain_password: "#{KEYCHAIN_PASSWORD}" # 키체인의 비밀번호를 제공합니다. 이 비밀번호는 키체인을 언락하는 데 사용됩니다.
      )

      # ✅ 프로비저닝 프로파일을 특정 위치에 설치하는 데 사용됩니다
      install_provisioning_profile(path: "Tuist/Signing/#{APP_NAME}.DEV.mobileprovision")
      install_provisioning_profile(path: "Tuist/Signing/#{APP_NAME}.PROD.mobileprovision")
    end

      
      #key_id: App Store Connect API 키의 ID입니다. 이는 Apple Developer 계정에서 생성된 키에 대한 고유 식별자입니다.
      
      #issuer_id: App Store Connect API 키의 발행자 ID입니다. 이는 Apple Developer 계정에서 생성된 키에 대한 발행자를 나타내는 고유 식별자입니다.
      
      #key_filepath: App Store Connect API 키 파일의 경로입니다. 이 파일은 개인 키로, .p8 확장자를 가진 키 파일일 것입니다.
      
      #duration: 선택적 매개변수로, 생성된 API 토큰의 수명을 지정합니다. 기본값은 1200초(20분)입니다. 필요에 따라 조정할 수 있습니다.
      
      #in_house: 선택적 매개변수로, true로 설정하면 In-House 앱 배포를 위한 키를 생성합니다. 기본값은 false입니다.
      
  desc "Push a new beta build to TestFlight"
  lane :beta do 

    # ✅ 앱스토어 커넥트 키 연결
    # App Store Connect API를 사용하기 위한 API 키를 로드하는 데 사용됩니다. 이를 사용하여 다른 fastlane 도구 및 액션에서 Apple 계정과 상호 작용할 수 있습니다. 
    app_store_connect_api_key(is_key_content_base64: true, in_house: false)

    # ✅ 빌드 넘버 증가
    increment_build_number(
        skip_info_plist: true,
        build_number: latest_testflight_build_number()+1,
        xcodeproj: "Projects/App/#{APP_NAME}.xcodeproj"
    )
  

    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{DEV_SCHEME}",
      export_method: "app-store" #  앱 스토어에 앱을 제출하기 위한 목적으로 아카이브를 내보냅니다.
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end