# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


# ✅ 기본 플랫폼을 ios 로 설정하여 fastlane [lane name] 으로 쉽게 실행가능.(원래 fastlane [platfrom name] [lane name] 으로 실행해야 함)
default_platform(:ios)


platform :ios do 
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "PrintingAlley-DEV")
    upload_to_testflight
  end
end
